spring:
  datasource:
    url: jdbc:mysql://alpha-server:63306/permission
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  session:
    store-type: redis
  redis:
    host: alpha-server
    password: 111111
    port: 6379
server:
  port: 8080