eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: projectA
  sleuth:
    sampler:
      percentage: 1
    enabled: true
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true