server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://alpha-server:63306/alpha-spring-security
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    database: 0
    host: alpha-server
    port: 6379
    pool:
      max-idle: 5

logging:
  level:
    org.springframework: INFO


jwt:
  header: Authorization
  secret: mySecret
  expiration: 21600000
  online: online-token
  codeKey: code-key
  tokenStartWith: Bearer