server:
  port: 6002

#spring:
#  zipkin:
#    rabbitmq:
#      queue: zipkin
#  sleuth:
#    sampler:
#      percentage: 0.2

spring:
  application:
    name: alpha-console-demo
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://alpha-server:63306/alpha?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true

ignore:
  urls:
    - /css/*.css
    - /js/*.js
    - /actuator/**
    - /hystrix/**
    - /metrics/**
    - /loggers/**





